### ISSUE TITLE
Add Achievement class

### ISSUE THREAD

**Issue by Im-Madhur-Gupta** [Team-9-Dev-Group/ESGFS#11]
* Parameters for this class can be general, figure them out.
* Methods -
    * Constructor
    * To display an achievement

**Comment by Im-Madhur-Gupta** [comment]
Kunal would be working on this.

**Comment by Im-Madhur-Gupta** [comment]
Kunal would be working on this.

**Comment by Kunaljainsethiya** [comment]
I am working on this issue

**Comment by Im-Madhur-Gupta** [comment]
@HetviSoni GG, closing now.
