### ISSUE TITLE
Add Semester Class

### ISSUE THREAD

**Issue by tirth5828** [Team-9-Dev-Group/ESGFS#2]
Attributes - 
Year 
Semester (Autumn or Winter)
Courses Taken
Achievements
Exams (a linked list to hold objects of Exam class)

Methods -
Getter and Setters for 
     -Year 
     -Semester (Autumn or Winter)
Add Achievement (Create the instance of Achievement class and add it to Achievements ArrayList)
createCourseList(year, semester) (will be created under another issue)

To store Achievements use an ArrayList. Achievement Arraylist will store objects of the Achievement class.

**Note -**
* You can ofc change the names slightly.
* You don't have to make Achievement class for this issue.
* Methods for the Exams LinkedList will be added under a separate issue.

**Comment by Im-Madhur-Gupta** [comment]
@foram-patel-0201 I have made some changes to this issue's description. So, please code it according to the new description.

**Comment by tirth5828** [comment]
Solved with PR #13
