### ISSUE TITLE
Club Joined Parameter 

### ISSUE THREAD

**Issue by Im-Madhur-Gupta** [Team-9-Dev-Group/ESGFS#20]
An instance of ClubActivity class will be pushed into an linkedlist called clubActivities inside of Student class.

As the name suggests this class would be used to store an activity of a club, clubs will be taken from a CONST Array / ArrayList of Strings which should be in Student class.

**Comment by tirth5828** [comment]
The above tagging of PR was a mistake, Please ignore it.
