### ISSUE TITLE
Create Class Diagram and Workflow Diagram

### ISSUE THREAD

**Issue by tirth5828** [Team-9-Dev-Group/ESGFS#3]

**Comment by Im-Madhur-Gupta** [comment]
**More than 1 person can work on this issue.**
Create a Hierarchical class diagram containing all of our classes as of now, find their details from other issues.

**Comment by HetviSoni** [comment]
jo bhi ye issue pe kaam kr rha ho wo yaha aa jao
https://www.figma.com/team_invite/redeem/TjfnhySmwSLnlZiRsOjreO

**Comment by Im-Madhur-Gupta** [comment]
@Kunaljainsethiya remake the class diagram for Semester class and once the Achievement class is done complete its class diagram as well.

**Comment by Im-Madhur-Gupta** [comment]
@Kunaljainsethiya Create proper class diagrams for Exam class and Achievement class, you may look at issues and PRs corresponding to these 2.

**Comment by Im-Madhur-Gupta** [comment]
Good work guys.
