### ISSUE TITLE
Create Student Class

### ISSUE THREAD

**Issue by Im-Madhur-Gupta** [Team-9-Dev-Group/ESGFS#4]
**Attributes** - (type attribute ke according dalna)
Name, student id, PG/UG, phone number, Academic probation and disciplinary probation.

**Methods**
-> Constructor
-> Sare attributes private karne he.
-> getter/setter dalna sabke liye
-> Probation check karne ke liye method dalna.

**Comment by rajasafi** [comment]
Ye code ke liye mai le raha hu

**Comment by Im-Madhur-Gupta** [comment]
Cool.
