### ISSUE TITLE
Create Course Class and createCourseList method for Semester class

### ISSUE THREAD

**Issue by tirth5828** [Team-9-Dev-Group/ESGFS#8]
Attributes - 
Department
Instructor1
Instructor2
Code
Credits
Time Code

Methods -
Getters and Setters

Next,
Create a method for Semester class that generates a CourseList upon taking year and semester as parameters.

**Comment by Abhay-Jagtap4** [comment]
I want to work on this issue.

**Comment by Im-Madhur-Gupta** [comment]
@Abhay-Jagtap4 bro the department field has been created in the semester class.

**Comment by Im-Madhur-Gupta** [comment]
@Abhay-Jagtap4 Good work bro ✌️
